Add automated python tests for stella. (#136)
* Create flag <print_extra_info_to_terminal> to suppress write statements to the terminal.

* Do not print <btor> to the geometry output file, since it is not calculated for VMEC equilibria.

* Clean-up the Github automated tests for push/pull requests.

* Create automated python tests for stella.

- Renamed "tests/integrated" to "tests/automated_stella_tests".
- Create 4 automated python tests for stella:
      - test 1: Check whether stellar runs and writes the output files.
      - test 2: Check whether the Miller geometry is calculated correctly.
      - test 3: Check whether the VMEC geometry is calculated correctly.
      - test 4: Check whether each term of the gyrokinetic equation is calculated correctly.

* Removed the <scripts> directory, so move <build_pfunit.sh> to <tests/unit/>

* Changed default lu_option to the local option, since it's typically the most efficient.

* Add more tests to the stella automatic testing.

-  Enable running on 2 nodes
-  Put common functions in a module

* Separate module to launch local stella runs.

* Add comments to the init_g variables.

* Cleaned-up automated stella tests.

- Created a module that contains the functions to run stella
- Updated the ReadMe file
- Cleaned up the input files.
- Added tests for the initialization of the distribution function

* Enforce reality condition correctly.

- Update the corresponding numerical tests.

* Added automatic tests for the diagnostics.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,12 +1,64 @@
-name: Tests
+# Run these tests automatically on Github
+# on every push and pull request.
+name: StellaTests
 on: [push, pull_request]
 
+# We run the in a bash shell
 defaults:
   run:
     shell: bash
 
+# Define the tests, for now we only have <standard_tests>
+# where we define 3 seperate workflows in matrix/config/name
+# For each of these workflows we need to perform the same
+# initial steps: <Install dependencies>, <System information>
+# Next, only the step corresponding to the test will be executed.
 jobs:
-  standard_tests:
+        
+  # Build stella with Make in debug mode, here the python tests do not work!
+  # Specifically, the flush statement in mini_libstell's 
+  # read_wout_mod.F module in the readw_and_open() routine breaks 
+  # when reading a VMEC equilibirium during the python tests.
+  test1:
+    runs-on: ubuntu-latest
+    env:
+      OMPI_MCA_rmaps_base_oversubscribe: yes
+      MPIRUN: mpiexec -np
+    strategy:
+      fail-fast: false
+      matrix:
+        config: 
+          - name: "Make stella in debug mode"  
+    steps:
+      - name: Install dependencies
+        run: sudo apt update &&
+             sudo apt install -y
+                 gfortran
+                 make
+                 libfftw3-dev
+                 libnetcdf-dev
+                 libnetcdff-dev
+                 netcdf-bin
+                 python3
+                 python3-pip
+                 openmpi-bin
+                 libopenmpi-dev
+
+      - name: System information
+        run: |
+          cat /etc/*release
+          gfortran --version
+          nf-config --all
+      - uses: actions/checkout@v2 
+        
+      - name: Build stella in debug mode
+        run: |
+          set -ex
+          export GK_SYSTEM=gnu_ubuntu_debug
+          make -I Makefiles -j4
+
+  # Build stella with Make and run automatic fortran tests
+  test2:
     runs-on: ubuntu-latest
     env:
       OMPI_MCA_rmaps_base_oversubscribe: yes
@@ -15,10 +67,7 @@ jobs:
       fail-fast: false
       matrix:
         config:
-          - name: "Makefiles"
-          - name: "Makefiles, debug"
-            gk_system: gnu_ubuntu_debug
-          - name: "CMake"
+          - name: "Perform fortran tests of the stella code" 
     steps:
       - name: Install dependencies
         run: sudo apt update &&
@@ -41,13 +90,103 @@ jobs:
           nf-config --all
       - uses: actions/checkout@v2
 
-      - name: Install integrated test dependencies
-        run: pip3 install --user -r tests/integrated/requirements.txt
+      - name: Build stella 
+        run: |
+          set -ex
+          export GK_SYSTEM=gnu_ubuntu
+          make -I Makefiles -j4
 
-      - name: Build stella (Makefile)
-        if: ${{ contains(matrix.config.name, 'Makefile') }}
-        run: ./scripts/ci_build_and_run.sh ${{ matrix.config.gk_system }}
+      - name: Perform automated Fortran tests
+        run: |
+          set -ex
+          export GK_SYSTEM=gnu_ubuntu
+          make -I Makefiles -j4 build-pfunit-library
+          make -I Makefiles -j4 run-automated-fortran-tests 
+
+  # Build stella with Make and run automatic python tests
+  test3:
+    runs-on: ubuntu-latest
+    env:
+      OMPI_MCA_rmaps_base_oversubscribe: yes
+      MPIRUN: mpiexec -np
+    strategy:
+      fail-fast: false
+      matrix:
+        config:
+          - name: "Run stella and check the outputs numerically" 
+    steps:
+      - name: Install dependencies
+        run: sudo apt update &&
+             sudo apt install -y
+                 gfortran
+                 make
+                 libfftw3-dev
+                 libnetcdf-dev
+                 libnetcdff-dev
+                 netcdf-bin
+                 python3
+                 python3-pip
+                 openmpi-bin
+                 libopenmpi-dev
+
+      - name: System information
+        run: |
+          cat /etc/*release
+          gfortran --version
+          nf-config --all
+      - uses: actions/checkout@v2
+
+      - name: Install automated stella test dependencies
+        run: pip3 install --user -r tests/requirements.txt
+
+      - name: Build stella 
+        run: |
+          set -ex
+          export GK_SYSTEM=gnu_ubuntu
+          make -I Makefiles -j4 
+
+      - name: Perform numerical tests for stella with Python
+        run: |
+          set -ex
+          export GK_SYSTEM=gnu_ubuntu
+          make -I Makefiles run-automated-numerical-tests-for-stella
+        
+  # Build stella with CMake and run automatic Fortran tests
+  # Cmake has to run on 1 node or it will run into parallelisation errors
+  test4:
+    runs-on: ubuntu-latest
+    env:
+      OMPI_MCA_rmaps_base_oversubscribe: yes
+      MPIRUN: mpiexec -np
+    strategy:
+      fail-fast: false
+      matrix:
+        config: 
+          - name: "CMake stella"
+    steps:
+      - name: Install dependencies
+        run: sudo apt update &&
+             sudo apt install -y
+                 gfortran
+                 make
+                 libfftw3-dev
+                 libnetcdf-dev
+                 libnetcdff-dev
+                 netcdf-bin
+                 python3
+                 python3-pip
+                 openmpi-bin
+                 libopenmpi-dev
+
+      - name: System information
+        run: |
+          cat /etc/*release
+          gfortran --version
+          nf-config --all
+      - uses: actions/checkout@v2  
 
       - name: Build stella (CMake)
-        if: ${{ contains(matrix.config.name, 'CMake') }}
-        run: ./scripts/ci_cmake_build_and_run.sh
+        run: |
+          set -ex
+          cmake . -B build -DSTELLA_ENABLE_TESTS=on
+          cmake --build build -j1 --target check
