Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -56,9 +56,50 @@ jobs:
           set -ex
           export GK_SYSTEM=gnu_ubuntu_debug
           make -I Makefiles -j4
+  # Build stella with CMake and run automatic Fortran tests
+  # Cmake has to run on 1 node or it will run into parallelisation errors
+
+  test2:
+    runs-on: ubuntu-latest
+    env:
+      OMPI_MCA_rmaps_base_oversubscribe: yes
+      MPIRUN: mpiexec -np
+    strategy:
+      fail-fast: false
+      matrix:
+        config: 
+          - name: "CMake stella"
+    steps:
+      - name: Install dependencies
+        run: sudo apt update &&
+             sudo apt install -y
+                 gfortran
+                 make
+                 libfftw3-dev
+                 libnetcdf-dev
+                 libnetcdff-dev
+                 netcdf-bin
+                 python3
+                 python3-pip
+                 openmpi-bin
+                 libopenmpi-dev
+
+      - name: System information
+        run: |
+          cat /etc/*release
+          gfortran --version
+          nf-config --all
+      - uses: actions/checkout@v2  
+
+      - name: Build stella (CMake)
+        run: |
+          set -ex
+          cmake . -B build -DSTELLA_ENABLE_TESTS=on
+          cmake --build build -j1 --target check
+
 
   # Build stella with Make and run automatic fortran tests
-  test2:
+  test3:
     runs-on: ubuntu-latest
     env:
       OMPI_MCA_rmaps_base_oversubscribe: yes
@@ -104,7 +145,7 @@ jobs:
           make -I Makefiles -j4 run-automated-fortran-tests 
 
   # Build stella with Make and run automatic python tests
-  test3:
+  test4:
     runs-on: ubuntu-latest
     env:
       OMPI_MCA_rmaps_base_oversubscribe: yes
@@ -151,18 +192,17 @@ jobs:
           export GK_SYSTEM=gnu_ubuntu
           make -I Makefiles run-automated-numerical-tests-for-stella
         
-  # Build stella with CMake and run automatic Fortran tests
-  # Cmake has to run on 1 node or it will run into parallelisation errors
-  test4:
-    runs-on: ubuntu-latest
+  # Build stella with Make and run automatic python tests using MacOs operating system
+  test5:
+    runs-on: macOS-latest
     env:
       OMPI_MCA_rmaps_base_oversubscribe: yes
       MPIRUN: mpiexec -np
     strategy:
       fail-fast: false
       matrix:
-        config: 
-          - name: "CMake stella"
+        config:
+          - name: "Run stella and check the outputs numerically using MacOs operating system" 
     steps:
       - name: Install dependencies
         run: sudo apt update &&
@@ -183,10 +223,20 @@ jobs:
           cat /etc/*release
           gfortran --version
           nf-config --all
-      - uses: actions/checkout@v2  
+      - uses: actions/checkout@v2
 
-      - name: Build stella (CMake)
+      - name: Install automated stella test dependencies
+        run: pip3 install --user -r tests/requirements.txt
+
+      - name: Build stella 
         run: |
           set -ex
-          cmake . -B build -DSTELLA_ENABLE_TESTS=on
-          cmake --build build -j1 --target check
+          export GK_SYSTEM=macosx
+          make -I Makefiles -j4 
+
+      - name: Perform numerical tests for stella with Python
+        run: |
+          set -ex
+          export GK_SYSTEM=macosx
+          make -I Makefiles run-automated-numerical-tests-for-stella
+        
